apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helloworld
  name: helloworld
  namespace: test1
spec:
  replicas: 12
  selector:
    matchLabels:
      app: helloworld
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloworld
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
        args: ["sleep", "1d"]
        ports:
        - containerPort: 80
status: {}
