apiVersion: v1
kind: Service
metadata:
  name: helloworld-service  # Change this to your desired service name
  namespace: test1  # Ensure it matches your deployment namespace
spec:
  selector:
    app: helloworld  # This should match the labels in your Deployment
  ports:
    - protocol: TCP
      port: 80   # The port inside the cluster
      targetPort: 80 # The port your app is listening on inside the pod
  type: ClusterIP  # This makes the service internal to the cluster
